### ISSUE TITLE
Windows usage, can it be?

### ISSUE THREAD

**Issue by petroShved** [usatenko/DjiMini2RCasJoystick#1]
Can i use this script on windows 11? And how?

**Comment by usatenko** [comment]
Unfortunately no, as it uses linux device subsystem and uinput lib to communicate with DJI RC.

For windows take a look at https://github.com/hjstn/miniDjiController it uses pyvjoy library instead.
In case you would like to make DJI Mini 2 RC work with windows you can use CRCs from my code but change the part which communicates with the device to be windows friendly.

Hope this helps.
