### ISSUE TITLE
Support for buttons

### ISSUE THREAD

**Issue by martonmiklos** [usatenko/DjiMini2RCasJoystick#2]
Hi all!

Would it be possible to add support for buttons?

I dumped the data array for the periodic DUML query, but the button presses does not alter it.
Do you have any information how the analog messages DUML command was figured out?
Using the DJI Simulator and sniffing the serial traffic, or it was done on the Android app?

**Comment by usatenko** [comment]
interesting, honestly, I do not remember why I did not take the data for buttons, I will check and update here

**Comment by martonmiklos** [comment]
Yeah in the meantime I looked after the DJI simulator, and the Mini2 remote is not supported in it. Interestingly there are folks out there who simulate XBox game controller based on the reverse engineered protocol 🤣

**Comment by usatenko** [comment]
yes, simulator does not support, this is why it needs to be manually switched to a controller mode.
XBox controller is just a different option of joystick, can be simulated also I believe (in case it will be possible to read the buttons...)

**Comment by Pixxxxel** [comment]
Hello!

I've been trying to get button information from the remote as well. It looks like the byte array which is returned does not contain anything about buttons. All the known commands ("get info" and "simulator mode enable") have the same cmd_type and cmd_set. Do you think it will be a good idea to try 254 other cmd_ids on these cmd type and set in order to find out if button information could be requested by any of them or i have a large chance to brick my remote?

**Comment by martonmiklos** [comment]
Well I would still try to figure out that how did these DUML commands figured out. By reverse engineering the firmware of the app itself?

**Comment by Pixxxxel** [comment]
If we look back in history, yes, the first set of bytes was found by looking at remote and dji app talk. Here is the link https://github.com/Matsemann/mDjiController/issues/3

However i have no idea who came up with send_duml method and how they found out which bytes are responsible for all the stuff. But the classification seems pretty correct. Also the protocol changed a lot for rc-n1 as mDjiController has incredibly different messages (AND THEY HAVE BUTTONS!!)

**Comment by martonmiklos** [comment]
> If we look back in history, yes, the first set of bytes was found by looking at remote and dji app talk. Here is the link [Matsemann/mDjiController#3](https://github.com/Matsemann/mDjiController/issues/3)
> 
> However i have no idea who came up with send_duml method and how they found out which bytes are responsible for all the stuff. But the classification seems pretty correct. Also the protocol changed a lot for rc-n1 as mDjiController has incredibly different messages (AND THEY HAVE BUTTONS!!)

Do you know if the button presses are detectable somehow by the Android app? maybe we could route the serial port with a gadget OTG driver with some Linux board and could sniff the serial traffic.

**Comment by Pixxxxel** [comment]
Oh, that's a good question. I know there is (maybe the only) simulator-like game on android called simuDrone and it isn't able to detect buttons. However, if we look at flight logs, at least we have info about cine / normal / sport profile. But it's hard to say either this information is from controller or grom the drone

**Comment by martonmiklos** [comment]
> Oh, that's a good question. I know there is (maybe the only) simulator-like game on android called simuDrone and it isn't able to detect buttons. However, if we look at flight logs, at least we have info about cine / normal / sport profile. But it's hard to say either this information is from controller or from the drone

I jumped on the Android bandwagon lately and I do not have OTG cable yet, but in the DJI GO app there is not anything like remote test or something?

**Comment by Pixxxxel** [comment]
I use dji fly with my mini 3 and i haven't seen such features in this app

**Comment by Pixxxxel** [comment]
There is another repository where send_duml is used. I'd really want to ask the creator of this method a couple of questions and probably it's either usatenko or IvanYaky https://github.com/IvanYaky/DJI_RC-N1_SIMULATOR_FLY_DCL

**Comment by Pixxxxel** [comment]
> > If we look back in history, yes, the first set of bytes was found by looking at remote and dji app talk. Here is the link [Matsemann/mDjiController#3](https://github.com/Matsemann/mDjiController/issues/3)
> > However i have no idea who came up with send_duml method and how they found out which bytes are responsible for all the stuff. But the classification seems pretty correct. Also the protocol changed a lot for rc-n1 as mDjiController has incredibly different messages (AND THEY HAVE BUTTONS!!)
> 
> Do you know if the button presses are detectable somehow by the Android app? maybe we could route the serial port with a gadget OTG driver with some Linux board and could sniff the serial traffic.

I think i found something related to dji traffic parsing. Have a look at this https://wiki.dji-rev.com/howto/dumlprinter

**Comment by martonmiklos** [comment]
We are likely using the 'RC Simulate Flight Mode Set' for enable (0x24) and the 'RC Channel Params Get' for polling:
https://github.com/o-gs/dji-firmware-tools/blob/master/comm_dissector/wireshark/dji-dumlv1-proto.lua#L132

There are some other commands code which might be useful to poke with.

**Comment by Pixxxxel** [comment]
> We are likely using the 'RC Simulate Flight Mode Set' for enable (0x24) and the 'RC Channel Params Get' for polling: https://github.com/o-gs/dji-firmware-tools/blob/master/comm_dissector/wireshark/dji-dumlv1-proto.lua#L132
> 
> There are some other commands code which might be useful to poke with.

Wow, that's an amazing piece of information! Thank you!
Unfortunately, the description of commands doesn't sound like something we need. Only "[0x04] RC Physical Channel Parameter Get" caught my attention, but that can be just anything else. Worth a try anyway.

**Comment by Pixxxxel** [comment]
So i tried a couple of commands and here are the results:
- 0x04 ('RC Physical Channel Parameter Get') returns about the same info about sticks and camera wheel, but does not contain any data about buttons. In fact it is only 30 bytes instead of 38 bytes for 0x01
- 0x1a ('RC Control Mode Get') does not refer to the center cine / normal / sport mode slider
- 0x24 ('RC Simulate Flight Mode Set') luckily does not need to be set to 0 as simulator mode is reseted to null when you reboot remote

So far i've ran out of ideas what else to try but the comment to 0x48 is a bit suspicious

**Comment by usatenko** [comment]
The only thing that can be read so far is a roller wheel at the left side

**Comment by usatenko** [comment]
Good news, I found it.
The button values are under command 27.
<img width="563" alt="image" src="https://github.com/usatenko/DjiMini2RCasJoystick/assets/1710344/9c18a69a-3dc2-4671-b8f2-0ae76524142f">
<img width="262" alt="image" src="https://github.com/usatenko/DjiMini2RCasJoystick/assets/1710344/59a54cb0-4670-43f2-8150-a30b1290f256">

**Comment by usatenko** [comment]
For example the answer of this duml packet with "Fn" button pressed and released is:
![image](https://github.com/usatenko/DjiMini2RCasJoystick/assets/1710344/80136c52-265e-4543-838f-5d8872b58604)

**Comment by usatenko** [comment]
Top right button:
![image](https://github.com/usatenko/DjiMini2RCasJoystick/assets/1710344/44d7c7bb-da2a-4380-9099-903a24be6d1c)

Just need some time to implement it.

**Comment by usatenko** [comment]
The change is implemented, all 4 buttons can be used with joystick.
https://github.com/usatenko/DjiMini2RCasJoystick/commit/1c2e6f3e3eb363ee01f2e9b61305bd6d3a57c72d
I am not sure I used right names of buttons, I can change if you tell me the correct names, though I believe they can be mapped in a simulator. Current mappings are:
- uinput.BTN_PINKIE,
- uinput.BTN_TRIGGER,
- uinput.BTN_THUMB,
- uinput.BTN_THUMB2,
<img width="664" alt="image" src="https://github.com/usatenko/DjiMini2RCasJoystick/assets/1710344/132f0c28-f901-4b98-9aab-d9ac8b6855ae">

**Comment by Pixxxxel** [comment]
Great job! I’m a little jealous I haven’t discovered that yesterday, I’ve tried bunch of other commands, but not 0x27 :)

I’ve seen the left big button referred as “go_home_button” in the file with command list. The upper left button could be called “multifunctional_button”, trigger on top right - “recording_start_button” and I’ve never used small button on the right with camera drawing yet so I have no clue what’s it for

**Comment by usatenko** [comment]
> I’ve seen the left big button referred as “go_home_button” in the file with command list.
I mean I am not sure which standard joystick buttons should be mapped to these RC buttons. They all listed here:
https://docs.huihoo.com/doxygen/linux/kernel/3.7/include_2uapi_2linux_2input_8h.html
