### ISSUE TITLE
Using pyenv for Python 3.11 distros

### ISSUE THREAD

**Issue by jim3692** [usatenko/DjiMini2RCasJoystick#3]
I tried to use this on Arch Linux, which uses Python 3.11 by default, but I was getting an error in this line:

```python
_libsuinput_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "_libsuinput" + sysconfig.get_config_var("SO")))
```

This seems to be related with this issue: https://github.com/tuomasjjrasanen/python-uinput/issues/44

My solution was:
- Install pyenv from here: https://github.com/pyenv/pyenv
- Download Python 3.10.4 by running `pyenv install 3.10.4`
- Set it as default for this project with `pyenv local 3.10.4`
- Create a Python Virtual Environment with `python -m venv .`
- Install the dependencies in the venv with `bin/pip install -r requirements.txt`
- Then run `sudo bin/python main.py -p /dev/ttyACM0`

After that, the controller was recognized by both `jstest-gtk` ([AUR](https://aur.archlinux.org/packages/jstest-gtk-git)) and Steam, allowing me to play Liftoff.

**Comment by usatenko** [comment]
thank you, I will try it on 3.11, will check the Ubuntu's env
