### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by 2black0** [usatenko/DjiMini2RCasJoystick#6]
Can this also be used to send data from Python via remote and then be received by the drone?

**Comment by usatenko** [comment]
When the RC is in simulator mode it can't be used to control the drone. Only in simulator mode it can communicate with Python app.
As far as I know it uses OcuSync v2 protocol, that is proprietary and it will not be an easy thing to inject something to it.
I also know that changing color of led on the drone can be controlled from the DJI APP and therefore some function may be attached to the drone like to throw some payload and be controlled from the APP.
But, of course, it is not as useful as sending raw bytes from python directly, unfortunately I do not see a way how to do it.
